import Head from 'next/head'
import { Text, Center, Box } from '@chakra-ui/react'
import Navbar from '../components/Navbar'
import '@fontsource/quicksand/600.css'
import '@fontsource/quicksand/700.css'

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

      <Center mt="1rem">
        <Box backgroundColor="#525252" borderRadius="0.75rem" paddingY="1rem" paddingX="1.8rem" id="upper-desc">
          <Text color="white" fontSize="1.8rem" fontWeight="600" textAlign="center">My blog</Text>
        </Box>
      </Center>
    </>
  )
}

export default Home
